--------------------------------------------------------
--  File created - Thursday-March-05-2020
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence DELIVERY_STATUS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CARRIER"."DELIVERY_STATUS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 14101 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PACKAGES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CARRIER"."PACKAGES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PACKAGES_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "CARRIER"."PACKAGES_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 198721 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PLANNED_ROUTES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CARRIER"."PLANNED_ROUTES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 58321 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TIMESETTINGS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CARRIER"."TIMESETTINGS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table DELIVERY_POINTS
--------------------------------------------------------

  CREATE TABLE "CARRIER"."DELIVERY_POINTS"
   (	"ID" NUMBER(10,0),
	"POINT_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DELIVERY_STATUS
--------------------------------------------------------

  CREATE TABLE "CARRIER"."DELIVERY_STATUS"
   (	"OPERATION_DATE" DATE,
	"PACKAGE_REF" NUMBER(10,0),
	"POINT_REF" NUMBER(10,0),
	"STATUS_REF" NUMBER(5,0),
	"ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PACKAGES
--------------------------------------------------------

  CREATE TABLE "CARRIER"."PACKAGES"
   (	"ID" NUMBER(10,0),
	"ACCEPTANCE_DATE" DATE,
	"START_POINT" NUMBER(10,0),
	"END_POINT" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLANNED_ROUTES
--------------------------------------------------------

  CREATE TABLE "CARRIER"."PLANNED_ROUTES"
   (	"ID" NUMBER(10,0),
	"PACKAGE_REF" NUMBER(10,0),
	"POINT_NUMBER" NUMBER(3,0),
	"POINT_REF" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STATUSES
--------------------------------------------------------

  CREATE TABLE "CARRIER"."STATUSES"
   (	"ID" NUMBER(5,0),
	"STATUS_NAME" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIMESETTINGS
--------------------------------------------------------

  CREATE TABLE "CARRIER"."TIMESETTINGS"
   (	"START_TIME" DATE,
	"ITERATION_NUMBER" NUMBER(5,0),
	"ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View CURRENT_DELIVERY_STATUS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CARRIER"."CURRENT_DELIVERY_STATUS" ("OPERATION_DATE", "PACKAGE_REF", "POINT_REF", "STATUS_REF", "ID") AS
  select ds."OPERATION_DATE",ds."PACKAGE_REF",ds."POINT_REF",ds."STATUS_REF",ds."ID" from carrier.delivery_status ds join (select id,max(operation_date) from delivery_status group by id) dsmax
on ds.id=dsmax.id
;
--------------------------------------------------------
--  DDL for Index DELIVERY_POINTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CARRIER"."DELIVERY_POINTS_PK" ON "CARRIER"."DELIVERY_POINTS" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PACKAGES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CARRIER"."PACKAGES_PK" ON "CARRIER"."PACKAGES" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STATUSES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CARRIER"."STATUSES_PK" ON "CARRIER"."STATUSES" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger DELIVERY_STATUS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CARRIER"."DELIVERY_STATUS_TRG"
BEFORE INSERT ON DELIVERY_STATUS
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT DELIVERY_STATUS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CARRIER"."DELIVERY_STATUS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PACKAGES_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CARRIER"."PACKAGES_TRG"
BEFORE INSERT ON PACKAGES
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PACKAGES_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CARRIER"."PACKAGES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PLANNED_ROUTES_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CARRIER"."PLANNED_ROUTES_TRG"
BEFORE INSERT ON PLANNED_ROUTES
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PLANNED_ROUTES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CARRIER"."PLANNED_ROUTES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TIMESETTINGS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CARRIER"."TIMESETTINGS_TRG"
BEFORE INSERT ON TIMESETTINGS
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CARRIER"."TIMESETTINGS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table DELIVERY_POINTS
--------------------------------------------------------

  ALTER TABLE "CARRIER"."DELIVERY_POINTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CARRIER"."DELIVERY_POINTS" MODIFY ("POINT_NAME" NOT NULL ENABLE);
  ALTER TABLE "CARRIER"."DELIVERY_POINTS" ADD CONSTRAINT "DELIVERY_POINTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PACKAGES
--------------------------------------------------------

  ALTER TABLE "CARRIER"."PACKAGES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CARRIER"."PACKAGES" MODIFY ("ACCEPTANCE_DATE" NOT NULL ENABLE);
  ALTER TABLE "CARRIER"."PACKAGES" MODIFY ("START_POINT" NOT NULL ENABLE);
  ALTER TABLE "CARRIER"."PACKAGES" ADD CONSTRAINT "PACKAGES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLANNED_ROUTES
--------------------------------------------------------

  ALTER TABLE "CARRIER"."PLANNED_ROUTES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATUSES
--------------------------------------------------------

  ALTER TABLE "CARRIER"."STATUSES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CARRIER"."STATUSES" ADD CONSTRAINT "STATUSES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
